### PR TITLE
add japanese language

### PR DESCRIPTION
**Pull request by soralis0912**
SSIA

### CODE REVIEW

**Comment by libxzr** [comment]
Thanks for your contribution!
I have just merged another PR so can you please add translation for it too?

**Comment by soralis0912** [comment]
@libxzr sorry missing branch.
reopen PR request.

**Comment by soralis0912** [comment]
@libxzr ok!

**Comment by soralis0912** [comment]
@libxzr added translation

**Comment by rivahere** [comment]
> Thanks for your contribution! I have just merged another PR so can you please add translation for it too?

it was really good

**Pull request merged**
