### PR TITLE
UI Designing: Try on Material Design

### PR DESCRIPTION
**Pull request by ShiSheng233**
Credit: [MDIX](https://github.com/MaterialDesignInXAML) 

Still have some problems.

Also the `TabControl` isn't have a good look.

Preview:

image

image

### CODE REVIEW

**Comment by ShiSheng233** [comment]
The designing still have a lot of problems, we should set the value of the size of some of the elements exactly.

**Review by MlgmXyysd — CHANGES_REQUESTED** [review]
Useless and unsightly `-2`

**Comment by libxzr** [comment]
Rework tab control wen

**Comment by Laulan56** [comment]
kawaii design

**Comment by MlgmXyysd** [comment]
> kawaii design

~~绒绒~~ design

**Comment by Laulan56** [comment]
> > kawaii design
> 
> ~绒绒~ design

绒绒 cat design

**Pull request closed without merging**
